spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:Students
    username: ${datasourseUsername}
    password: ${datasoursePassword}
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
security:
  jwt:
    secret: ${securityJwtSecret}
    access: ${securityJwtAccess}
    refresh: ${securityJwtRefresh}
  admin:
    data:
      key: ${adminDataKey}
