spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    name: atom_app
    url: jdbc:h2:mem:atom_app
    username: ${datasourseUsername}
    password: ${datasoursePassword}
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
security:
  jwt:
    secret: ${securityJwtSecret}
    access: ${securityJwtAccess}
    refresh: ${securityJwtRefresh}
  admin:
    data:
      key: ${adminDataKey}
      adminUsername: ${adminUsername}
      adminPassword: ${adminPassword}
      adminName: ${adminName}
